---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - l2.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  - gateway.yaml

patches:
  - patch: |-
      - op: remove
        path: /status
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.16.2
    releaseName: cilium
    namespace: kube-system
    valuesInline:
      cluster:
        name: "cluster"
        id: 1

      autoDirectNodeRoutes: true

      bgpControlPlane:
        enabled: false

      gatewayAPI:
        enabled: true

      socketLB:
        hostNamespaceOnly: true

      ingressController:
        enabled: false
        loadbalancerMode: shared
        defaultSecretNamespace: kube-system

      k8sServiceHost: 192.168.3.5
      k8sServicePort: 6443

      rollOutCiliumPods: true
      localRedirectPolicy: true

      kubeProxyReplacement: true

      loadBalancer:
        algorithm: "maglev"
        mode: "dsr"

      bandwidthManager:
        enabled: true
        bbr: true

      l2announcements:
        enabled: true
        leaseDuration: "120s"
        leaseRenewalDeadline: "10s"
        leaseRetryPeriod: "5s"
        loadBalancer:

      bpf:
        masquerade: true
        tproxy: true

      l7Proxy: true

      cni:
        exclusive: true

      ipam:
        mode: "kubernetes"

      operator:
        rollOutPods: true

      routingMode: "native"
      ipv4NativeRoutingCIDR: 10.2.0.0/16

      hubble:
        enabled: true
        tls:
          auto:
            enabled: true
            method: cronJob
            schedule: "0 0 1 */7 *"
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          label: grafana_dashboard
          namespace: monitoring
          labelValue: "1"
          annotations: {}
        metrics:
          enabled:
            - dns:query;ignoreAAAA
            - drop
            - tcp
            - flow
            - port-distribution
            - icmp
            - http
        relay:
          enabled: true
          rollOutPods: true
        ui:
          enabled: true
          rollOutPods: true
          ingress:
            enabled: false
            className: cilium
            hosts:
              - "hubble.jordande.beer"
            tls:
              - hosts:
                  - "*.jordande.beer"
                secretName: wildcard-tls

      securityContext:
        capabilities:
          ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
          cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
      cgroup:
        autoMount:
          enabled: false
        hostRoot: /sys/fs/cgroup

commonAnnotations:
  meta.helm.sh/release-name: cilium
  meta.helm.sh/release-namespace: kube-system
labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: true 

