---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.14.0-rc.1
    releaseName: cilium
    namespace: kube-system
    valuesInline:
      cluster:
        name: "cluster"
        id: "1"

      bgpControlPlane:
        enabled: true

      k8sServiceHost: 192.168.3.126
      k8sServicePort: 6443

      rollOutCiliumPods: true
      localRedirectPolicy: true

      kubeProxyReplacement: "strict"
      kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

      loadBalancer:
        algorithm: "maglev"
        mode: "dsr"

      bandwidthManager:
        enabled: true
        bbr: true

      bpf:
        masquerade: true
        tproxy: true

      l7Proxy: true

      cni:
        exclusive: false

      enableCnpStatusUpdates: true
      endpointStatus:
        enabled: true
        status: "policy"

      ipam:
        mode: "kubernetes"

      operator:
        rollOutPods: true

      autoDirectNodeRoutes: true
      ipv4NativeRoutingCIDR: 10.244.0.0/16
      tunnel: "disabled"
      containerRuntime:
        integration: containerd

      hubble:
        enabled: true
        tls:
          auto:
            enabled: true
            method: cronJob
            schedule: "0 0 1 */7 *"
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          label: grafana_dashboard
          namespace: monitoring
          labelValue: "1"
          annotations: {}
        metrics:
          enabled:
            - dns:query;ignoreAAAA
            - drop
            - tcp
            - flow
            - port-distribution
            - icmp
            - http
        relay:
          enabled: true
          rollOutPods: true
        ui:
          enabled: true
          rollOutPods: true
          ingress:
            enabled: true
            annotations:
            #  external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            #  external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
            className: cilium
            hosts:
              - &host "hubble.lab.home.jordandebeer.com"
            tls:
              - hosts:
                  - *host
                secretName: wildcard-tls

      securityContext:
        capabilities:
          ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
          cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
      cgroup:
        autoMount:
          enabled: false
        hostRoot: /sys/fs/cgroup

commonAnnotations:
  meta.helm.sh/release-name: cilium
  meta.helm.sh/release-namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: Helm
