---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab
spec:
  blocks:
    - start: 192.168.3.250
      stop: 192.168.3.254
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  loadBalancerIPs: true
