apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
spec:
    secretTemplates:
        - name: cloudflare-api-key
          stringData:
              api-key: ENC[AES256_GCM,data:znd3C4UDT03KzSocThh1Rui01nubot8XonwVpKCVDklRyfIKfv69dw==,iv:51LOO6uRvITU1XKBjsTlZyjOHenyGWyvbzrpwp05oWU=,tag:S2wInnC7fMLFKBtSFXmNlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfmgqg5wzxnztmhdqt4g9k9l3qk7hsj86qf3u0xy685nwh489duqedf07m
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cTZoOUpoRWoraDhiUHZY
              bTRIVnU5VHlPNzVKVHZBa0taVzBmMHJ4U0c4CkZkY2ZBMjJyZjlJOWlxemFLMXl2
              dDlkcUdJV3VJQXZYMDVhankzRm5zOUUKLS0tIFFIOFYwT29vTU9Mb2V1TDZlUHhK
              c1grREhOajlMbDdLVWZ0Zi9aS1F0MjgKCKUjh4jXyXpOtEkyw8tDk5Uu8Ye/QqXU
              L1AKeTx2xcYGHSivPEUeipY3sLzxmJwFQbNk+Rh5quQinEG1/Yw61g==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T02:29:19Z"
    mac: ENC[AES256_GCM,data:iiX3b3aTNrIaQbVjqba1F9IxXUtfbNpkTPDD9fH89iug5OjlptzWP4LhTiWA/1XsmrGvci/y9s57zbH5P86t9d+ih+EChaEzhPj2hw7ZF9K5bCcf8J2tz1qnc4kstM3E4T6FU9jC6Qb//aHupTRTGbuVaYWjpKY2DiEq4oiqvhg=,iv:tqx6VxbQFXWQ/dso3RxJ9sx17Ih89uzaANJHcbts2MY=,tag:dKkZPvOXepkYg+psEOQFMQ==,type:str]
    pgp: []
    encrypted_regex: ^(secret|secretboxencryptionsecret|key|token|secretboxEncryptionSecret|contents|bootstraptoken|stringData)$
    version: 3.7.3
