creation_rules:
  - encrypted_regex: "^(secret|secretboxencryptionsecret|key|token|secretboxEncryptionSecret|contents|bootstraptoken|stringData)$"
    age: >-
      age1nfmgqg5wzxnztmhdqt4g9k9l3qk7hsj86qf3u0xy685nwh489duqedf07m
