apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ns.yaml
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.67.1/bundle.yaml
  - prometheus.yaml
