apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/prometheus-operator/kube-prometheus?ref=release-0.13
patches:
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: prometheus-k8s
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: grafana
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: alertmanager-main
        namespace: monitoring
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: node-exporter
