cluster:
  name: "cluster"
  id: "1"

k8sServiceHost: 192.168.3.5
k8sServicePort: 6443

rollOutCiliumPods: true
localRedirectPolicy: true

kubeProxyReplacement: "strict"
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

loadBalancer:
  algorithm: "maglev"
  mode: "dsr"

bandwidthManager:
  enabled: true
  bbr: true
bpf:
  masquerade: true
  tproxy: true

l7Proxy: true

cni:
  exclusive: false

enableCnpStatusUpdates: true
endpointStatus:
  enabled: true
  status: "policy"

ipam:
  mode: "kubernetes"

operator:
  rollOutPods: true

autoDirectNodeRoutes: true
tunnel: "disabled"
ipv4NativeRoutingCIDR: 10.2.0.0/16
containerRuntime:
  integration: containerd

hubble:
  enabled: false

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
