---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: mayastor
    repo: https://openebs.github.io/mayastor-extensions/
    releaseName: mayastor
    namespace: mayastor
    valuesInline:
      loki-stack.persistence.storageClassName: manual
      etcd.persistence.storageClassName: manual
