apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-triple-replica
parameters:
  ioTimeout: "60"
  protocol: nvmf
  repl: "3"
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Delete
volumeBindingMode: Immediate
