---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/isindir/sops-secrets-operator/master/config/crd/bases/isindir.github.com_sopssecrets.yaml
patches:
  - target:
      name: sops-secrets-operator
      kind: Deployment
      version: .*
    path: sops-namespace-patch.yaml
  - target:
      name: sops-secrets-operator
      kind: ServiceAccount
      version: .*
    path: sops-namespace-patch.yaml
helmCharts:
  - name: sops-secrets-operator
    repo: https://isindir.github.io/sops-secrets-operator/
    releaseName: sops-secrets-operator
    namespace: sops
    valuesInline:
      extraEnv:
        - name: SOPS_AGE_RECIPIENTS
          value: age1nfmgqg5wzxnztmhdqt4g9k9l3qk7hsj86qf3u0xy685nwh489duqedf07m
        - name: SOPS_AGE_KEY_FILE
          value: "/mnt/keys.txt"
      secretsAsFiles:
        - name: age-keys
          mountPath: "/mnt/"
          secretName: age-keys
