---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - istio-gateway.yaml
patches:
  - patch: |-
      - op: replace
        path: /apiVersion
        value: policy/v1
    target:
      group: policy
      version: v1beta1
      kind: PodDisruptionBudget
  - patch: |-
      - op: replace
        path: /apiVersion
        value: autoscaling/v2
    target:
      group: autoscaling
      version: v2beta2
      kind: HorizontalPodAutoscaler
  - patch: |-
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
    target:
      kind: Deployment
      name: istiod
  - patch: |-
      - op: add
        value: "ignore"
        path: /metadata/annotations/client.lifecycle.config.k8s.io~1mutation
    target:
      kind: "ValidatingWebhookConfiguration"
helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istiod
    namespace: istio-system
    valuesInline:
      meshConfig:
        extensionProviders:
          - name: oauth2-proxy
            envoyExtAuthzHttp:
              service: oauth2-proxy.istio-system.svc.cluster.local
              port: 80
              headersToUpstreamOnAllow:
                - path
                - x-auth-request-email
                - x-auth-request-preferred-username
              headersToDownstreamOnDeny:
                - content-type
                - set-cookie
              includeRequestHeadersInCheck:
                - authorization
                - cookie
                - x-auth-request-groups
              includeAdditionalHeadersInCheck: # Optional for oauth2-proxy to enforce https
                X-Auth-Request-Redirect: "https://%REQ(:authority)%%REQ(:path)%?rd=%REQ(:authority)%%REQ(:path)"
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istio-ingressgateway
    namespace: istio-system
