apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lab-tunnel-secret
    namespace: cloudflared
spec:
    secretTemplates:
        - name: lab-tunnel-secret
          stringData:
            credentials.json: ENC[AES256_GCM,data:N5gUk1YGocvBt+ItiSL8AZ25v/B6oDWtRYeZqrXJFC+kIWwHeSTNc48yCvuMNXS6DHdAlbKUmGqaW47bs0lfap0VJ/whe2Sk3ePbZrWHi8aG3wmHfAGVADRNDbhJEcVAvpZwGOTSrHUQsBS9Gvwe3kSCap8ev1PSMXaUZjc7SHHTruCZxTaxxEiIh3Ge2Sz+QXUJO5wVwIt9GIqWfMhTbKJVUcMvbA==,iv:HgXjRv8flew9bxOWbvw/PxBMx4HB8Krfpyf3IWrHHJU=,tag:F4CqsbLEaZFIZRHiRWmmpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfmgqg5wzxnztmhdqt4g9k9l3qk7hsj86qf3u0xy685nwh489duqedf07m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRHF3QkRtRlV0bVBGUkRV
            T3VLVE81dDhiR0dUdE5TMWZJNEpMVEwvOFY4CllweXZwZ3VlVzA4czlUNUpOTzJV
            NXJkZTJUT3JqOENZTXV0WE9Mc1dSV1kKLS0tIDI4bEVURld2VlB4ZWVCMDJmekRL
            VFlEbUdLZlNTVTVScGdrbS9GVVptWjAKQOQodFcE3rTMSKR3T88xb+iBejc7r2Xr
            T8fXgIgSJo/qDo8Kx7n+FJJh8N21Vp9bronhcv+hDihyhcxpJk9x2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T21:50:17Z"
    mac: ENC[AES256_GCM,data:hShuFn8yp6ajV5YCSEGD96vBJx5er6YJuWvlTLUY8q2zFoy6BPedekRtaEdiZzHs4wmAdwuoHU7C5EhGTCHHxkfaAVSrNUdLwDIAmHO5LJnJ9Fj59n3YubS2ulk013Fr3q/3wzBNQ22LZIgxJUYWqLsXKaGyqpDoRYgn7b6tvhM=,iv:RyGwXXC9XfRt3zMlEEAwvpZTfJtx+6dtvdeqEwif46k=,tag:43pVW8RQ8JCk+Zxs8kXQow==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.3
