apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lab-tunnel-secret
    namespace: cloudflared
stringData:
    credentials.json:
        AccountTag: ENC[AES256_GCM,data:qhUBLskWlG0YvFuHY1AiIH5D1a+4kHkS/xSk1JyR1/A=,iv:TDv0Cd4yA0P1c5sQEWABC4CZS1IO+2W6ndxsvf0meck=,tag:wqQVck4eSz7WXMag3OgAyQ==,type:str]
        TunnelSecret: ENC[AES256_GCM,data:YxqGxSgcXSkzAkTlFZL7DgVcq0MbzfRgrQTbaW1ZKCxya5DfMZysNhMVV5Bqk5Ki,iv:RJdB9n/VaPmp2PzpeMu39WYlFDC85jdiVDopRG82cEM=,tag:TD77GEYNKlTQlK/VVGVzYA==,type:str]
        TunnelID: ENC[AES256_GCM,data:swGZpZkEZUIKaGFgjt79m4tEDw7SOrzP38VnDaqE6PgEbSdO,iv:UcWR5uZO60zZWLP4UYizQEKOUiQLfeKMPSuWytOEaR4=,tag:MugZzhE9aJ2t9H80w8wpPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfmgqg5wzxnztmhdqt4g9k9l3qk7hsj86qf3u0xy685nwh489duqedf07m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZzZRajZoSkR1TVA5WWJG
            cDdnRjI0amp1RW9iY2hUdHdQUFk2SUIzMDM0Cmx3NEdoMkkxa3IwVDI2bCtLVHBD
            RjdSc1RNcmp2aUJGUTNuYmVPa2R1RTQKLS0tIGZPTWZza09DWVZEbnowVFdadXRn
            YWdkejhBVytCL0FVSkQzT2dEMEpNa1UKmQ2JbaMdwMaOZGd1UhXgjun2xUheXOqT
            GU17h2KyUnkfnNMWDjuMd0DFtsEA3bqIAWZ0jj0dU6Zex94aGFtplw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T11:41:33Z"
    mac: ENC[AES256_GCM,data:3CPwXtFitw7dYCz/p510B5aXJeyE7HqYDWILcSR6SVpTOxszwd7AcrS9koAq5bW7g6yP5hGfG08zBkMUCR/1eKppG5Yg4vPUTNEdUZQ6RmUVKMXE0qRVeeApLfoFz4mFm67WOdwn/1+PAhFOSAF0ImK+6XymrwuMW0qEheJmBfY=,iv:hNwiVtf5DkRivtF1eZsJ+x62LdxMJSIl8uTyv5uil/0=,tag:hLzjyX/rM0ENeCi9YSnmYg==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.3
