apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lab-tunnel-secret
    namespace: cloudflared
spec:
    secretTemplates:
        - name: lab-tunnel-secret
          stringData:
            credentials.json: ENC[AES256_GCM,data:Dgvu7G/o6ebA4uYqFHbPQihWd0O7zhtCRmHT+X1hfjaLbfoWEkTUWl2cRJyDnLuTyW/Yev/dX7/oaKp3Th7d8tlQ3CEqvd1QQGPvak8Px+pH3Mv5hzEQvqXe0YEBbEsw6ES63ZRyA71oLzcnDxxQ6BLPZURWhA+ViKHce52s0T5wjn5D3ycOchDbHZ1CYP2ArjXHVSqtngjvclqaYBClwy9AHxcmbA==,iv:mcsCS0JkSMQvky714/x4X25YRiDGL5A5H0038lz7zIE=,tag:Um5AFb/8V5eMxmyRUPqDew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfmgqg5wzxnztmhdqt4g9k9l3qk7hsj86qf3u0xy685nwh489duqedf07m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUTB0MDZkbndFMlJKd3Qw
            SkxsdTJPaXh3YjRvbmJzZkdmQnlvMHphU1dZCjNUT2Q3M1h3d1JjZjQxWWRLUzQ2
            UVcvc1hzL25ScnIrTEtGUm9iQWVPczAKLS0tIGNIc3NIei9RRExla2FEYzdOb3Jz
            RUg5QXJVaDQ5YW9iVmhMd3RLelBqNGsKXyeYyPEkXYDi9sA5D+SOAw8v73aa9O8w
            U2k3K1U/H/IdtUMSmJKkoagAORW9qQ77FUIuny5JyHvtGBgOKyhFfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T13:36:09Z"
    mac: ENC[AES256_GCM,data:kscVQcGWJEZ1U/Mg8T1NDdBWLr9UpCWKZkxaoy8EOvNSPaAihV/Rg1PRsjwY/FEjjgLOoJhrXNIkG073sSLnSOVqE7EikE7GyIyogifWUcucBmo+/5xVKVAwe1NroXlLRegmnKj0APTIKg48pOJifsCiIqXNMSmG+kEsT+Sj40g=,iv:5K8bQKsvjpnGB/uotXTYXH3JRbkS0FyFif6pS7wSwB8=,tag:uBanQayy5YdeRRLPz355SA==,type:str]
    pgp: []
    encrypted_regex: ^(secret|secretboxencryptionsecret|key|token|secretboxEncryptionSecret|contents|bootstraptoken|stringData)$
    version: 3.7.3
