---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - cloudflare-tunndel-secret.enc.yaml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: cloudflared
