apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - operator-oauth.enc.yaml
helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    namespace: kube-system
    version: 1.69.52
    includeCRDs: true
