apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.6.0
    releaseName: longhorn
    namespace: longhorn-system
    valuesInline:
      defaultDataPath: /var/mnt/nvme
patches:
  - patch: |-
      - op: remove
        path: /status
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
