apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  defaultBackend:
    service:
      name: longhorn-frontend
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - longhorn
