apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel
data:
  visibility: |
    ExternalIP:
      class: cilium
      gateway: kube-system/gateway
      service: kube-system/cilium-gateway-gateway
    ClusterLocal:
      class: cilium
      gateway: kube-system/gateway
      service: kube-system/cilium-gateway-gateway
