apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: knative-serving
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
