apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-key
          stringData:
            api-key: ENC[AES256_GCM,data:wj6+2on7aUlgoNfoy3KW8TjqmQiqihsdjlRHT2YeiF9lJrEyZzrpzA==,iv:kECQjAlXjZefwQhAFVt5oWLzQZZccMPyY93dqVlfqRA=,tag:rUzUPsrwaXcm/vuUf1jnqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfmgqg5wzxnztmhdqt4g9k9l3qk7hsj86qf3u0xy685nwh489duqedf07m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZEVqQzV1VVFicnc0emN2
            ZU9Fa1BkbFk4TjFjbjE4eFJqOWdLNlpDbXcwCm0xMDFiSXBzWUxpUm80aHU5T3Fi
            dGYzbVRnZUEwMUZEWUlmb2NKaUs3dkkKLS0tIGVpRmxsRjdrNW15a2twZXNleTdC
            MmFsZHk3TmYrbEo4WnA0SnNTSFNxYnMK1R43E8i+i75YIHHKq+tCOX9dH63X/RXh
            VQaPAbumicj1gRgLquLnBGMoLtKvf/kzEGk5biqrqPYP4xem78XvJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T23:56:13Z"
    mac: ENC[AES256_GCM,data:zWqelNDJjtXjsSmD4+3RpuNAQxhcflpOslUrgn6OqISA/o5QoaKk+JMmsS7F/S/XsyMagNfDDvVu8yDtu01dxDDKdFJNz7XTJKqTjmBK4bOZjZnrglabUTo5aCAKTJOEZ3HHdQLaX+TrhXg1RftrRhNsKVLEizXAV2tbLLhqTnk=,iv:G3DU2sWHmtOtmSPj6nlIKOUodzcknScLdZvmu8P2qiQ=,tag:Yj2DEozSgVi0K8s+P/NDnQ==,type:str]
    pgp: []
    encrypted_regex: ^(secret|secretboxencryptionsecret|key|token|secretboxEncryptionSecret|contents|bootstraptoken|stringData)$
    version: 3.7.3
